# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5c671b4c7c2d98f07bca916ebbda7fcbfc7b0bf5795fa3f7db5f8cbd88fe21cd2f9d3bf4a59f09dd494b29a7754d4cb9dd4667bbdc304a37a845c5a0837628e

test:
  secret_key_base: ece3606df12c725dce68122a9236b14e3bd288ce5232128830543455922cc18a8745fa0842d1f629ab2dda9bb4048a1cf262d0f374e861f1897d30328d175696

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
